version: 0.1

phases:
  install:
    commands:
      - go get github.com/Masterminds/glide
  pre_build:
    commands:
      - glide install
  build:
    commands:
      - go build
  post_build:
    commands:
      - env


# phases:
#   install:
#     commands:
#       - hogehogehogehoge
#       - mkdir -p $GOPATH/{bin,src}
#       - curl https://glide.sh/get | sh
#   pre-build:
#     commands:
#       - echo prebuildstart
#       - PATH=$PATH:$GOPATH/bin
#       - echo prebuildend
#   build:
#     commands:
#       - hoge -a
#       - echo buildstrat
#       - glide install
#       - go build
#   post_build:
#     commands:
#       - echo Build completed on `date`
#

# artifacts:
#   type: zip
#   files:
#     - oshirase
